Tests for 'Your Rides' page
Amali-Tech/aegis_testAutomation pull request #15
Opened 2022-04-08 16:42 UTC by lindakumah

2022-04-10 04:42 UTC, JerryHukpati requested changes
this PR has been rejected. there are too many changes for one PR and moreover I can see you worked on unrelated test on this branch. rebase your branch with dev for the latest changes and work on only "your-rides" tests in this branch.

2022-04-10 04:42 UTC, JerryHukpati commented on cypress/fixtures/amali-change-password.data.js
> +}
why is change password data is in this branch too? please remove

2022-04-10 04:42 UTC, JerryHukpati commented on cypress/integration/tests/AccountSettings/amali-change-password.spec.js
> + const{email, oldPassword, newPassword, confirmNewPassword, confirmNewPassword2} = changePasswordData;
based on the above comment, if you are using the change password data in this test, rebase your branch with dev for the latest changes.

2022-04-11 10:37 UTC, JerryHukpati requested changes

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/AccountSettings/amali-system-preference.spec.js
> +      cy.get('.v-tab').contains('System Settings').click()
```suggestion
      cy.contains('System Settings').click()
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/AccountSettings/amali-system-preference.spec.js
> +      cy.get('.v-tab').contains('System Settings').click()
to avoid the dynamic class which might break the test in future

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +    })
what does this test do?? and it has no assertion as well

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +
```suggestion
       cy.clearCookies({ domain: null })
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +       cy.intercept('https://**/create new password').as('setNewPassword')
there is no end point that has "spaces". this intercept will surely not work

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +     it.only("should check that 6 digit reset code is required", () => {
```suggestion
     it("should check that 6 digit reset code is required", () => {
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +       cy.get('.ae-link').contains("Forgot password?").click();
```suggestion
       cy.contains("Forgot password?").click();
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +       cy.get('#submit_button').contains('Confirm Email').click()
```suggestion
       cy.get('#submit_button').click()
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +       cy.get('#confirmCodeBtn').contains('Confirm Code').click()
```suggestion
       cy.get('#confirmCodeBtn').click()
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +
remove empty line

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
> +    it.only('reset password', () => {
```suggestion
    it('reset password', () => {
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
> +    it.only('reset password', () => {
test case name is not descriptive enough

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
> +      cy.get('.ae-link').contains('Forgot password?').click()
```suggestion
      cy.contains('Forgot password?').click()
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
> +      cy.get('#submit_button').contains('Confirm Email').click()
```suggestion
      cy.get('#submit_button').click()
```

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
>      })
reset password is not fully implemented so how is this possible?

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/YourRides/amali-your.rides.spec.js
> +//         .should('have.css', 'color', 'rgb(0, 0, 0)')
make sure it is fixed before we can merge to dev

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/support/commands.js
> +  cy.get('[data-cy=loginEmail]').type(email)
this changes you made here, broke the login tests

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/support/commands.js
> +  cy.checkEmail(loginEmail)
refer to earlier comment

2022-04-11 10:37 UTC, JerryHukpati commented on cypress/integration/tests/YourRides/amali-your.rides.spec.js
> +      cy.wait(1000)
why wait

2022-04-11 10:47 UTC, lindakumah commented on cypress/integration/tests/AccountSettings/amali-system-preference.spec.js
> +      cy.get('.v-tab').contains('System Settings').click()
Resolved

2022-04-11 10:47 UTC, lindakumah commented on cypress/integration/tests/AccountSettings/amali-system-preference.spec.js
> +      cy.get('.v-tab').contains('System Settings').click()
Got it!

2022-04-11 10:50 UTC, lindakumah commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +    })
It selects any of the options 'This week, This Month, This Year, All Time' and statistics from User's rides are displayed based on the option that is chosen

2022-04-11 10:51 UTC, lindakumah commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +
Please what's the difference here?

2022-04-11 12:06 UTC, lindakumah commented on cypress/integration/tests/ResetPassword/amali-password-reset-validation.spec.js
> +       cy.intercept('https://**/create new password').as('setNewPassword')
Removed

2022-04-11 13:06 UTC, lindakumah commented on cypress/integration/tests/ResetPassword/amali-password-reset.spec.js
>      })
Test has been taken out

2022-04-11 13:20 UTC, lindakumah commented on cypress/support/commands.js
> +  cy.checkEmail(loginEmail)
What's wrong with this?

2022-04-11 17:42 UTC, JerryHukpati approved these changes

2022-04-11 17:42 UTC, merged