Feature/single ride
Amali-Tech/aegis_testAutomation pull request #21
Opened 2022-04-29 10:36 UTC by felixportuphy

2022-04-30 03:31 UTC, JerryHukpati requested changes
clean up the filter rides file based on the comments I made. I also see some console logs still in the file and also the comments are not necessary. If you do all these changes, I'm sure you'll be able to reduce the number of lines.

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +    it('Navigates through Tabs', () => {
test case name not descriptive enough

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let jsonData = res.response
I don't think there's a need for a variable declaration here. just do everything in the assertion.

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        expect(jsonData.statusCode).to.eq(200)
```suggestion
        expect(res.response.statusCode).to.eq(200)
```

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let total = jsonData.body.total
```suggestion
        let total = res.response.body.total
```

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let lastRide = jsonData.body.data[total - 1]
make the necessary changes for firstRide and lastRide too

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        cy.get('.ae-ride-card').should('have.length', total)
I'm not convinced with this assertion. It is not measured against anything. i.e this assertion could always pass.

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        cy.get('.ae-ride-card').should('have.length', total)
see above comments

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        cy.get('.ae-ride-card').should('have.length', total)
see above comments

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +let firstRid, lastRid
I'm surprised you didn't rename these variables

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/_helpers/update-profile.js
> +
too many unnecessary lines in this block. the comment on line 56 as well I don't see it use

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/_helpers/filter-rides.js
> +}
I don't think you are using this at the moment. you can delete it for now.

2022-04-30 03:31 UTC, JerryHukpati commented on cypress/integration/_helpers/date.js
> +  const timeStampMs = date.getTime()
timeStampMs??? consider better naming of variables. e.g timeInMilliSeconds, dateString

2022-04-30 03:31 UTC, JerryHukpati commented on cypress-open.json
> +  "watchForFileChanges": false
don't forget to remove this please.

2022-05-03 12:16 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +    it('Navigates through Tabs', () => {
Resolved

2022-05-03 12:16 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let jsonData = res.response
Done

2022-05-03 12:16 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        expect(jsonData.statusCode).to.eq(200)
Done

2022-05-03 12:17 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let total = jsonData.body.total
Done

2022-05-03 12:17 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +        let lastRide = jsonData.body.data[total - 1]
Done

2022-05-03 12:17 UTC, felixportuphy commented on cypress/integration/tests/Rides/amali-filter-rides.spec.js
> +let firstRid, lastRid
Done

2022-05-03 12:17 UTC, felixportuphy commented on cypress/integration/_helpers/update-profile.js
> +
Resolved

2022-05-03 12:18 UTC, felixportuphy commented on cypress/integration/_helpers/filter-rides.js
> +}
Done

2022-05-03 12:18 UTC, felixportuphy commented on cypress/integration/_helpers/date.js
> +  const timeStampMs = date.getTime()
Done

2022-05-03 12:18 UTC, felixportuphy commented on cypress-open.json
> +  "watchForFileChanges": false
Done

2022-05-30 14:59 UTC, closed without merging