Pr/quick fixes
Amali-Tech/aegis_testAutomation pull request #24
Opened 2022-07-06 09:37 UTC by felixportuphy

2022-07-06 18:08 UTC, JerryHukpati requested changes

2022-07-06 18:08 UTC, JerryHukpati commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +      })
dynamic selectors

2022-07-06 18:08 UTC, JerryHukpati commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +  it('Should filter statistics', () => {
test name not descriptive

2022-07-06 18:08 UTC, JerryHukpati commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +        cy.get('.ae-value').eq(2).should('contain.text', response.body.data.summary.total_ride_duration)
dynamic selectors. do you have to do all these assertions for one test case?

2022-07-06 18:08 UTC, JerryHukpati commented on cypress/integration/tests/Single Ride/amali-single-ride.spec.js
> +  // })
remove commented out code

2022-07-18 15:44 UTC, felixportuphy commented on cypress/integration/tests/CheckEmail/amali-checkemail.spec.js
> +    cy.wait('@checkUser', { timeout: 5000 }).then((success) => {
Done

2022-07-18 16:15 UTC, felixportuphy commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +  it('Should filter statistics', () => {
Done

2022-07-18 16:17 UTC, felixportuphy commented on cypress/integration/tests/Single Ride/amali-single-ride.spec.js
> +  // })
Done

2022-07-21 08:02 UTC, JerryHukpati approved these changes

2022-07-21 12:13 UTC, merged