Profile page and Create Account
Amali-Tech/aegis_testAutomation pull request #4
Opened 2022-03-17 16:40 UTC by lindakumah

2022-03-18 16:13 UTC, JerryHukpati requested changes
add device names to your describes to differentiate desktop tests from mobile

2022-03-18 16:13 UTC, JerryHukpati commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
> +      cy.get('#confirm_password').type(newuser().confirm_password)
no need to use newuser().password etc. when you have already destructured the values in the newuser function

2022-03-18 16:13 UTC, JerryHukpati commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
> +      cy.get('.v-messages__message').its('length').should('be.gt', 0)
all dynamic classes should be replaced with static id's/datacy's. speak with the developers about this

2022-03-22 16:22 UTC, lindakumah commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
> +      cy.clearCookies({ domain: null })
Resolved

2022-03-22 16:22 UTC, lindakumah commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
> +    it('signs up with valid email and password', () => {
Resolved

2022-03-22 16:23 UTC, lindakumah commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
>  import { newuser } from 'cypress/fixtures/amali-create.account.data'
Resolved

2022-03-22 16:23 UTC, lindakumah commented on cypress/integration/tests/AccountCreation/amali-create.account.spec.js
> +    it('Signs up with a mismatched password', () => {
Resolved

2022-03-22 16:24 UTC, lindakumah commented on cypress/integration/tests/Profile/amali-userprofile.spec.js
> +    it('takes User to the Edit profile page', () => {
Done!

2022-03-22 19:45 UTC, JerryHukpati requested changes
the edit-profile test is breaking. let's work on this together tomorrow at the office. all comments on the other changes should also be fixed

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +// })
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
>        // select country
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      // })
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      // })
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      cy.get('[data-cy="address"]').as('addressField').type(address)
why are you chaining these in an alias if won't need it later?

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      cy.get('[data-cy="city"]').as('cityField').type(city)
refer to earlier comment on unused aliases

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove empty lines

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove empty line

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +    // })
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
>      })
add the validations/assertions to these test cases

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +    // // })
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove comment

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove empty line

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove empty line

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +
remove empty line

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +// defaultDevices.map((device) => {
if you are removing the test for mobile, add a multiline comment and explain why. clean up the test by removing all commented out code

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +    // const [w, h] = device.viewport
refer to earlier comment on devices

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      // cy.viewport(w, h)
refer to earlier comment on devices

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/integration/tests/EditProfile/amali-editprofile.spec.js
> +      // cy.viewport(w, h)
refer to earlier comment on devices

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/fixtures/amali-create.account.data.js
> +    email: 'aegis.tester+' +new Date().getTime().toString().slice(5, 9) + '@gmail.com',
```suggestion
    email: 'aegis.tester+' + new Date().getTime().toString().slice(5, 9) + '@gmail.com',
```

2022-03-22 19:45 UTC, JerryHukpati commented on cypress/fixtures/amali-checkemail.scenario.data.js
> +  nonexisting_email: 'aegistester+' +new Date().getTime() + '@gmail.com',
```suggestion
  nonexisting_email: 'aegistester+' + new Date().getTime() + '@gmail.com',
```

2022-03-23 09:01 UTC, lindakumah commented on cypress/support/commands.js
>  })
We can keep this one. Felix will take the other one out?

2022-03-23 09:06 UTC, lindakumah commented on cypress/fixtures/amali-create.account.data.js
> +    email: 'aegis.tester+' +new Date().getTime().toString().slice(5, 9) + '@gmail.com',
Done!

2022-03-23 18:50 UTC, JerryHukpati approved these changes
all good. this PR can be merged

2022-03-24 10:51 UTC, merged