Edit profile
Amali-Tech/aegis_testAutomation pull request #5
Opened 2022-03-21 22:04 UTC by felixportuphy

Edit profile and change password features ,assertions to be done

2022-03-23 08:09 UTC, JerryHukpati requested changes
the edit profile test can be found in Linda's PR as well. Fix all the comment and sort out the edit profile duplicate test and create a new PR

2022-03-23 08:09 UTC, JerryHukpati commented on cypress-open.json
> +  "defaultCommandTimeout": 10000,
don't push changes you make for debugging your test. your might end up breaking other tests. revert all changes you made to the cypress-open.json file

2022-03-23 08:09 UTC, JerryHukpati commented on cypress-open.json
> +  "retries": 0,
refer to earlier comment on cypress-open.json

2022-03-23 08:09 UTC, JerryHukpati commented on cypress-open.json
> +  "watchForFileChanges": false
remove

2022-03-23 08:09 UTC, JerryHukpati commented on cypress/fixtures/amali-changepassword.data.js
> +
remove empty line

2022-03-23 08:09 UTC, JerryHukpati commented on cypress/fixtures/amali-changepassword.data.js
> +
remove empty line

2022-03-23 08:09 UTC, JerryHukpati commented on cypress/integration/tests/AccountSettings/amali-001-change-password.spec.js
> +    it.only('Should  change user account password ', () => {
```suggestion
    it('Should  change user account password ', () => {
```

2022-03-23 08:09 UTC, JerryHukpati commented on cypress/support/commands.js
> +
remove empty line

2022-03-23 09:33 UTC, felixportuphy commented on README.md
> +
Resolved

2022-03-23 09:33 UTC, felixportuphy commented on cypress-open.json
> +  "defaultCommandTimeout": 10000,
Resolved

2022-03-23 09:37 UTC, felixportuphy commented on cypress-open.json
> +  "retries": 0,
Resolved

2022-03-23 09:38 UTC, felixportuphy commented on cypress-open.json
> +  "watchForFileChanges": false
Resolved

2022-03-23 09:39 UTC, felixportuphy commented on cypress/fixtures/amali-changepassword.data.js
> +
Resolved

2022-03-23 09:42 UTC, felixportuphy commented on cypress/integration/tests/AccountSettings/amali-001-change-password.spec.js
> +    it.only('Should  change user account password ', () => {
Resolved

2022-03-23 09:45 UTC, felixportuphy commented on cypress/support/commands.js
> +
Resolved

2022-03-24 08:29 UTC, nx-jeremiahhukpati requested changes
merge the login branch into dev and rebase your branch. Re-request the review for this PR after that. Accept changes from dev when doing the rebase. Let me know if any have issues doing the rebase.

2022-03-24 10:58 UTC, closed without merging